GestorLaboratorios/ViewModels/Inicio/ElementosPrestamoViewModel.cs
using System.Collections.Generic;

namespace GestorLaboratorios.ViewModels.Inicio
{
    public class ElementosPrestamoViewModel
    {
        public int IdReservaPrestamo { get; set; }
        public int IdEstadoReservaPrestamo { get; set; }
        public List<ElementosPrestamoViewModel> ListadoPrestamoElementos { get; set; }
        public int IdElemento { get; set; }
        public string PlacaElemento { get; set; }
        public string SerialElemento { get; set; }
        public string ModeloElemento { get; set; }
        public string MarcaElemento { get; set; }
        public int Entregado { get; set; }

        public string JsFuncion { get; set; }
    }
}

GestorLaboratorios/ViewModels/Inicio/InicioEstudianteViewModel.cs
using GestorLaboratorios.ViewModels.Configuracion;
using System;
using System.Collections.Generic;

namespace GestorLaboratorios.ViewModels.Inicio
{
    public class InicioEstudianteViewModel
    {
        public List<ElementoViewModel> ListadoDetalleElemento { get; set; }
        public int IdElemento { get; set; }
        public string TipoElemento { get; set; }
        public string Placa { get; set; }
        public string Serial { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Observacion { get; set; }

        public DateTime Fecha { get; set; }
        public string Profesor { get; set; }
        public string Materia { get; set; }

        public string JsFuncion { get; set; }

    }
}

GestorLaboratorios/ViewModels/Inicio/InicioViewModel.cs
using System;
using System.Collections.Generic;

namespace GestorLaboratorios.ViewModels.Inicio
{
    public class InicioViewModel
    {
        public List<InicioViewModel> ListadoPrestamo { get; set; }

        public int IdPrestamo { get; set; }
        public int IdTipoSolicitud { get; set; }
        public string TipoSolicitud { get; set; }
        public string Usuario { get; set; }
        public DateTime Fecha { get; set; }
        public string Profesor { get; set; }
        public string Materia { get; set; }
        public int ?IdEstado { get; set; }
        public string Estado { get; set; }

        public string JsFuncion { get; set; }
    }
}

GestorLaboratorios/Controllers/InicioController.cs
using GestorLaboratorios.Services;
using GestorLaboratorios.Settings;
using GestorLaboratorios.ViewModels.Inicio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace GestorLaboratorios.Controllers
{
    [ServiceFilter(typeof(VerifyUserAttribute))]
    public class InicioController : Controller
    {
        private readonly ConfiguracionRepositorio _configuracionRepositorio;
        private readonly InicioRepositorio _inicioRepositorio;
        private readonly IConfiguration _configuracion;
        Encrypter encrypter = new Encrypter();

        public InicioController(InicioRepositorio inicioRepositorio, ConfiguracionRepositorio configuracionRepositorio, IConfiguration configuration)
        {
            this._inicioRepositorio = inicioRepositorio;
            this._configuracionRepositorio = configuracionRepositorio;
            this._configuracion = configuration;
        }

        public IActionResult Inicio()
        {
            try
            {
                int idLaboratorio = int.Parse(HttpContext.Session.GetString("id_laboratorio"));

                var model = new InicioViewModel();

                if (TempData["funcionCambioEstadoReservaPrestamo"] is string respuestaCambioEstado)
                {
                    model.JsFuncion = respuestaCambioEstado;
                }

                model.ListadoPrestamo = _inicioRepositorio.ListadoPrestamo(idLaboratorio);
                return View(model);
            }
            catch (Exception)
            {
                return new RedirectResult("~/Login/Login");
            }
        }

        public IActionResult InicioEstudiante()
        {
            try
            {
                var model = new InicioEstudianteViewModel();

                model.ListadoDetalleElemento = _configuracionRepositorio.ListadoDetalleElemento(1, 1);

                if (TempData["mensajeCreacionReserva"] is string mensajeCreacionReserva)
                {
                    model.JsFuncion = mensajeCreacionReserva;
                }

                return View(model);
            }
            catch (Exception err)
            {
                return new RedirectResult("~/Login/Login");
            }
        }

        public IActionResult ElementosPrestamo(string IdPresEncrip, string IdEstadoEncrip)
        {
            try
            {
                int idPrestamo = int.Parse(encrypter.Decrypt(IdPresEncrip));
                int idEstado = int.Parse(encrypter.Decrypt(IdEstadoEncrip));
                var model = new ElementosPrestamoViewModel();
                model.IdReservaPrestamo = idPrestamo;
                model.ListadoPrestamoElementos = _inicioRepositorio.ListadoElementosPrestamo(idPrestamo);
                model.IdEstadoReservaPrestamo = idEstado;
                //model.ListadoPrestamoElementos.
                if (TempData["funcionEntregarElemento"] is string funcionEntregarElemento)
                {
                    model.JsFuncion = funcionEntregarElemento;
                }

                //model.ListadoPrestamoElementos.coun

                return View(model);
            }
            catch (Exception err)
            {
                return new RedirectResult("~/Login/Login");
            }
        }

        public bool EntregarElemento(int IdReservaPrestamo, string[] IdsELementos)
        {
            try
            {
                bool bRespuesta = _inicioRepositorio.EntregarElemento(IdReservaPrestamo, IdsELementos);

                string sMensaje = (bRespuesta) ? "Se entregaron correctamente los elementos" : "Error al entregar los elementos";
                string sIcono = (bRespuesta) ? "success" : "error";

                TempData["funcionEntregarElemento"] = $"mensaje('{sMensaje}','{sIcono}')";
                return true;
            }
            catch (Exception err)
            {
                return false;
            }
        }

        //public IActionResult CambioEstadoReservaPrestamo(string IdReservaPrestamoEncrip, string IdEstadoEncrip)
        //{
        //    try
        //    {
        //        int idReservaPrestamo = int.Parse(encrypter.Decrypt(IdReservaPrestamoEncrip));
        //        int idEstado = int.Parse(encrypter.Decrypt(IdEstadoEncrip));

        //        bool respuestaCambioEstado = _inicioRepositorio.CambioEstadoReservaPrestamo(idReservaPrestamo, idEstado);
        //        string sMensaje = (respuestaCambioEstado) ?:;

        //        TempData["respuestaCambioEstado"] = $"mensajeCambioEstado({respuestaCambioEstado.ToString().ToLower()});";
        //        return new RedirectToActionResult("Inicio", "Inicio", null);
        //    }
        //    catch (Exception err)
        //    {
        //        return StatusCode((int)HttpStatusCode.InternalServerError, err.ToString());
        //    }
        //}

        public bool CambiarEstadoReservaPrestamo(int IdPrestamoReserva, int IdEstado, bool Prestamo)
        {
            try
            {
                bool respuesta = _inicioRepositorio.CambiarEstadoReservaPrestamo(IdPrestamoReserva, IdEstado, Prestamo);

                string sMensaje = (respuesta) ? "Se cambió el estado correctamente" : "Error al cambiar el estado";
                string sIcono = (respuesta) ? "success" : "error";
                TempData["funcionCambioEstadoReservaPrestamo"] = $"mensaje('{sMensaje}','{sIcono}');";
                return respuesta;
            }
            catch (Exception err)
            {
                return false;
            }
        }

    }
}

GestorLaboratorios/Views/Inicio/ElementosPrestamo.cshtml
@model GestorLaboratorios.ViewModels.Inicio.ElementosPrestamoViewModel

@using GestorLaboratorios.Settings;

@inject Encrypter encrypter;

<script>

    function entregarElementos() {
        try {
            Pace.track(() => {
                var idsElementos = [];
                $("table").find("td#tdFiltro input:checked").each((index, item) => {
                    idsElementos.push(item.id);
                });

                var data = { IdReservaPrestamo:@Model.IdReservaPrestamo , IdsELementos: idsElementos };

                if (idsElementos.length > 0) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Content("~/Inicio/EntregarElemento")',
                        data: data,
                        success: (data) => {
                            $("#urlRecargar")[0].click();
                        },
                        error: (err) => {
                            console.log(err);
                        }
                    });
                } else {
                    mensaje("Debe seleccionar algún elemento", "error");
                }
            });

        } catch (err) {
            window.location.href = '@Url.Content("~/Login/Login")';
        }
    }

    function cerrarPrestamo() {
        try {
            $.ajax({
                type: "POST",
                url: '@Url.Content("~/Inicio/CambiarEstadoReservaPrestamo")',
                data: { IdPrestamoReserva : @Model.IdReservaPrestamo, IdEstado : 2, Prestamo:true},
                success: (data) => {
                    window.location.href = '@Url.Content("~/Inicio/Inicio")';
                },
                error: (err) => {
                    console.log(err);
                }
            });
        } catch (err) {
            window.location.href = '@Url.Content("~/Login/Login")';
        }
    }

    $(function () {


        if (@Model.IdEstadoReservaPrestamo ==1){
            var idsElementos = [];

            $("table").find("td#tdFiltro input").each((index, item) => {
                idsElementos.push(item.id);
            });

            if (idsElementos.length == 0) {
                $("#btnEntregarElementos").text("Cerrar").attr("onclick", "cerrarPrestamo();");
            }
        }

    });

    @Html.Raw(Model.JsFuncion)

</script>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <h3 class="mt-5">Elementos Reserva Prestamo # @Model.IdReservaPrestamo</h3>
            </div>
        </div>
        <a id="urlRecargar" style="display:none;" asp-controller="Inicio" asp-action="ElementosPrestamo"
           asp-route-IdPresEncrip="@encrypter.Encrypt(Model.IdReservaPrestamo.ToString())"
           asp-route-IdEstadoEncrip="@encrypter.Encrypt(Model.IdEstadoReservaPrestamo.ToString())">
        </a>

        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-12">
                @if (Model.IdEstadoReservaPrestamo == 1)
                {
                    <button id="btnEntregarElementos" class="btn btn-success" onclick="entregarElementos();">Entregar</button>
                }
                <a asp-controller="Inicio" asp-action="Inicio">
                    <input type="button" class="btn btn-danger" value="Volver" />
                </a>
            </div>
        </div>

        <div class="row" style="padding:2% 0;">
            <div class="col-lg-12 col-md-12 col-sm-12">
                @if (Model.ListadoPrestamoElementos != null)
                {
                    <table class="table-sm table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Placa</th>
                                <th>Serial</th>
                                <th>Modelo</th>
                                <th>Marca</th>
                                <th>Entregado</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var elemento in Model.ListadoPrestamoElementos)
                            {
                                <tr>
                                    <td id="tdFiltro">
                                        @if (elemento.Entregado == 0 && Model.IdEstadoReservaPrestamo == 1)
                                        {
                                            <input id="@encrypter.Encrypt(elemento.IdElemento.ToString())" type="checkbox" />
                                        }
                                    </td>
                                    <td>@elemento.PlacaElemento</td>
                                    <td>@elemento.SerialElemento</td>
                                    <td>@elemento.ModeloElemento</td>
                                    <td>@elemento.MarcaElemento</td>
                                    <td>@((elemento.Entregado == 1) ? "SI" : "NO")</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                }
                else
                {
                    <h1>Error al cargar los datos</h1>
                }
            </div>
        </div>
    </div>
</div>

GestorLaboratorios/Views/Inicio/Inicio.cshtml
@using GestorLaboratorios.Settings;

@model GestorLaboratorios.ViewModels.Inicio.InicioViewModel

@inject Encrypter encrypter;

<script type="text/javascript">

    @Html.Raw(Model.JsFuncion)

    function confirmarAceptarRechazar(mensaje, idReservaPrestamo, idEstado) {
        try {
            confirmar(`¿Desea ${mensaje} la reserva?`, () => {
                Pace.track(() => {
                    $.ajax({
                        type: "GET",
                        data: { IdPrestamoReserva: idReservaPrestamo, IdEstado: idEstado, Prestamo:false },
                        url: '@Url.Content("~/Inicio/CambiarEstadoReservaPrestamo")',
                        success: (data) => {
                            window.location.href = '@Url.Content("~/Inicio/Inicio")';
                        },
                        error: (err) => {
                            window.location.href = '@Url.Content("~/Login/Login")';
                        }
                    });
                });
            });

        } catch (err) {
            window.location.href = '@Url.Content("~/Login/Login")';
        }
    }

</script>

<div id="general">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h3 class="mt-5">Préstamos /</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    @if (Model.ListadoPrestamo != null && Model.ListadoPrestamo.Any())
                    {
                        <table class="table table-sm table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Usuario</th>
                                    <th>Tipo Solicitud</th>
                                    <th>Fecha</th>
                                    <th>Profesor</th>
                                    <th>Materia</th>
                                    <th>Estado</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var prestamo in Model.ListadoPrestamo)
                                {
                                    <tr>
                                        <td>@prestamo.IdPrestamo</td>
                                        <td>@prestamo.Usuario</td>
                                        <td>@prestamo.TipoSolicitud</td>
                                        <td>@prestamo.Fecha</td>
                                        <td>@prestamo.Profesor</td>
                                        <td>@prestamo.Materia</td>
                                        <td>@prestamo.Estado</td>
                                        <td>
                                            @*@if (prestamo.IdTipoSolicitud == 1 || (prestamo.IdTipoSolicitud == 2 && prestamo.Estado != null))*@
                                            @*{*@
                                            <a asp-controller="Inicio" asp-action="ElementosPrestamo"
                                               asp-route-IdPresEncrip="@encrypter.Encrypt(prestamo.IdPrestamo.ToString())"
                                               asp-route-IdEstadoEncrip="@encrypter.Encrypt(prestamo.IdEstado.ToString())">
                                                <img src="~/images/verMas.png" style="cursor:pointer;" title="Ver Elementos" />
                                            </a>
                                            @* } *@

                                            @if (prestamo.IdTipoSolicitud == 2 && prestamo.IdEstado == 4)
                                            {
                                                <img onclick="confirmarAceptarRechazar('aceptar',@prestamo.IdPrestamo,1);" src="~/images/aceptar.png" style="cursor:pointer;" title="Aceptar Reserva" />
                                                <img onclick="confirmarAceptarRechazar('rechazar',@prestamo.IdPrestamo,3);" src="~/images/rechazar.png" style="cursor:pointer;" title="Rechazar Reserva" />
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <h1>No hay préstamos ni reservas del día en curso</h1>
                    }
                </div>
            </div>

        </div>
    </div>

</div>

GestorLaboratorios/Views/Inicio/InicioEstudiante.cshtml
@model GestorLaboratorios.ViewModels.Inicio.InicioEstudianteViewModel;
@using GestorLaboratorios.Settings;

@inject Encrypter encrypter;


<script type="text/javascript">

    function cancelar() {
        try {
            $("#divReserva").css("display", "none");
        } catch (err) {
            window.location.href='@Url.Content("~/Login/Login")'
        }
    }



    function reserva() {
        try {
            $("#divReserva").css("display", "block");
        } catch (err) {
            window.location.href = '@Url.Content("~/Login/Login")';
        }
    }


    function crearReserva(dataForm) {
        try {
            var arregloIdsElementos = [];
            $("#tablaCheck").find("td#tdFiltro input:checked").each((index, item) => {
                arregloIdsElementos.push(item.id);
            });

            if (arregloIdsElementos.length > 0) {
                var data = $(dataForm).serializeArray();
                data.push({ name: "IdsElementos", value: arregloIdsElementos });
                data.push({ name: "Prestamo", value: false });

                Pace.track(() => {
                    $.ajax({
                        type: "POST",
                        data: data,
                        url: '@Url.Content("~/Configuracion/CrearPrestamo")',
                        success: (data) => {
                            window.location.href = '@Url.Content("~/Inicio/InicioEstudiante")';
                        },
                        error: (err) => {
                            window.location.href = '@Url.Content("~/Login/Login")';
                        }
                    })
                });
            }
            else {
                mensaje("Debe seleccionar algún elemento", "error");
            }
        } catch (err) {
            window.location.href = '@Url.Content("~/Login/Login")';
        }
    }

    @Html.Raw(Model.JsFuncion);

</script>

<div id="general" class="row">

    <div class="col-lg-12 col-sm-12 col-sm-12">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <h1>Reservas</h1>
            </div>
        </div>

        <div id="divReserva" style="display:none;" class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <form id="formularioCrearPrestamo" onsubmit="crearReserva(this); return false;">
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <label>Fecha</label>
                        <input asp-for="Fecha" class="form-control" id="fechaInicio" placeholder="Fecha inicio" type="date" />
                    </div>

                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <label>Profesor</label>
                        <input asp-for="Profesor" class="text-capitalize form-control" id="profesor" />
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <label>Materia</label>
                        <input asp-for="Materia" class="text-capitalize form-control" id="materia" />
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                        <button type="submit" class="btn btn-success">Guardar</button>
                        <input type="button" class="btn btn-danger" value="Cancelar" onclick="cancelar();" />
                    </div>
                </form>
            </div>
        </div>

        @if (Model.ListadoDetalleElemento != null && Model.ListadoDetalleElemento.Any())
        {
            <div id="divBotonReserva" class="row">
                <div class="col-lg-2 col-md-2 col-sm-12">
                    <button class="btn btn-primary" onclick="reserva();">Reseva</button>
                </div>
            </div>
        }

        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                @if (Model.ListadoDetalleElemento != null && Model.ListadoDetalleElemento.Any())
                {
                    <table id="tablaCheck" class="table table-sm table-bordered table-striped">
                        <thead>
                            <tr>
                                <td></td>
                                <td scope="col">Placa</td>
                                <td scope="col">Tipo Elemento</td>
                                <td scope="col">Serial</td>
                                <td scope="col">Modelo</td>
                                <td scope="col">Marca</td>
                            </tr>

                            @foreach (var ele in Model.ListadoDetalleElemento)
                            {
                                <tr>
                                    <td id="tdFiltro">
                                        <input id="@encrypter.Encrypt(ele.IdElemento.ToString())" type="checkbox" />
                                    </td>
                                    <td>@ele.Placa</td>
                                    <td>@ele.TipoElemento</td>
                                    <td>@ele.Serial</td>
                                    <td>@ele.Modelo</td>
                                    <td>@ele.Marca</td>
                                </tr>
                            }
                        </thead>
                    </table>
                }
                else
                {
                    <h1>No hay elementos disponibles</h1>
                }
            </div>
        </div>
    </div>
</div>